routes/admin.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'auth'], function () {
    Route::any('/login', ['middleware' => 'guest', 'uses' => 'AuthController@login'])->name('admin.auth.login');
    Route::any('/register', ['middleware' => 'guest', 'uses' => 'AuthController@register'])->name('admin.auth.register');
    Route::post('/logout', ['middleware' => 'auth:backend', 'uses' => 'AuthController@logout'])->name('admin.auth.logout');
});

Route::middleware('auth:backend')->group(function () {
    Route::get('/', 'DashboardController@index')->name('admin.index');
    Route::resource('hosts', 'HostController')->middleware('can:manage.hosts');
    Route::prefix('appointments')->group(function () {
        Route::get('/', 'AppointmentsController@index')->name('admin.appointments.index');
        Route::get('/{id}/show', 'AppointmentsController@show')->name('admin.appointments.show');
        Route::post('/create', 'AppointmentsController@store')->middleware('can:manage.appointments')->name('admin.appointments.store');
        Route::get('/create', 'AppointmentsController@create')->middleware('can:manage.appointments')->name('admin.appointments.create');
        Route::post('/{id}/update', 'AppointmentsController@update')->middleware('can:manage.appointments')->name('admin.appointments.update');
        Route::post('/{id}/reserve', 'AppointmentsController@reserve')->name('admin.appointments.reserve');
        Route::post('/{id}/cancel', 'AppointmentsController@cancel')->name('admin.appointments.cancel');
    });
});

routes/web.php
<?php


use Firebase\JWT\JWT;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth:backend')->namespace('Frontend')->group(function () {
    Route::get('/', function () {
        return redirect()->route('admin.index');
    })->name('index');
    Route::get('/meeting/{id}/join', 'MeetingsController@handle')->name('meetings.join');
    Route::get('/meeting/{id}/host', 'MeetingsController@handle')->name('meetings.host');
});

app/Http/Controllers/Admin/HostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class HostController extends Controller
{

    public $data = array();

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = User::hosts();
        if ($this->data['query'] = $request->get('q')) {
            $query->where('first_name', 'like', '%' . $this->data['query'] . '%')
                ->orWhere('last_name', 'like', '%' . $this->data['query'] . '%')
                ->orWhere('email', 'like', '%' . $this->data['query'] . '%');
        }
        $this->data['hosts'] = $query->paginate();
        return view('admin.hosts.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['host'] = null;
        return view('admin.hosts.edit', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'email' => 'required|unique:users',
            'first_name' => 'required',
            'last_name' => 'required',
            'password' => 'required|min:6'
        ]);
        $request->merge(['role' => 'host']);
        $user = User::create($request->all());
        session()->flash('status', 'Host Created Successfully');
        return redirect()->route('hosts.show', $user->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['host'] = User::findOrFail($id);
        return view('admin.hosts.edit', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $request->validate([
            'email' => 'required|unique:users,email,'.$id,
            'first_name' => 'required',
            'last_name' => 'required',
        ]);
        $user->update($request->all());
        session()->flash('status', 'Host Updated Successfully');
        return redirect()->route('hosts.show', $id);
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/admin/hosts/edit.blade.php
@extends('admin.layouts.app')
@section('title',$host ? 'Update Host' : 'Create New Host')
@section('content')
    <div class="content">
        <div class="container-fluid justify-content-center align-items-center">
            @include('admin.layouts.messages')

            <div class="row">
                <div class="col-md-2">
                    <a href="{{route('hosts.create')}}" class="btn btn-primary">Add New Host</a>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">
                                {{$host ?  "Update Host" : "Add New Host"}}
                            </h4>
                        </div>
                        <div class="card-body">
                            @if($host)
                                <form method="POST" action="{{route('hosts.update', $host->id)}}">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="put" id="">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">First Name</label>
                                                <input name="first_name"
                                                       value="{{\Request::old('first_name', $host->first_name)}}"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">First Name</label>
                                                <input name="last_name"
                                                       value="{{\Request::old('last_name', $host->last_name)}}"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">First Name</label>
                                                <input name="email" value="{{\Request::old('email', $host->email)}}"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary pull-right">Update Host</button>
                                </form>
                            @else
                                <form method="POST" action="{{route('hosts.store')}}">
                                    {{csrf_field()}}
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">First Name</label>
                                                <input name="first_name"
                                                       value="{{\Request::old('first_name', '')}}"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">Last Name</label>
                                                <input name="last_name"
                                                       value="{{\Request::old('last_name', '')}}"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">Email</label>
                                                <input name="email" value="{{\Request::old('email', '')}}"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="bmd-label-floating">Password</label>
                                                <input name="password" minlength="6"
                                                       type="text"
                                                       class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary pull-right">Create Host</button>
                                </form>
                            @endif
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
    </script>
@endpush

resources/views/admin/hosts/index.blade.php
@extends('admin.layouts.app')
@section('title','Hosts')
@section('content')
    <div class="content">
        <div class="container-fluid">
            @include('admin.layouts.messages')
            <div class="row float-right">
                <div class="col-md-2">
                    <a href="{{route('hosts.create')}}" class="btn btn-primary">Add New Host</a>
                </div>
            </div>
            <form action="{{route('hosts.index')}}" method="get">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="bmd-label-floating">Host</label>
                            <input type="text" autocomplete="off" class="form-control" name="q" value="{{$query}}">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <button class="btn btn-primary">Filter</button>
                    </div>
                </div>
            </form>
            @if(count($hosts))
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title ">Hosts</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead class="">
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Email</th>
                                        </thead>
                                        <tbody>
                                        @foreach($hosts as $host)
                                            <tr>
                                                <td>
                                                    <a href="{{route('hosts.show', $host->id)}}">
                                                        {{$host->first_name}}
                                                    </a>
                                                </td>
                                                <td>{{$host->last_name}}</td>
                                                <td>{{$host->email}}</td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-lg-12 text-center">
                        Page
                        {{ $hosts->currentPage() }}
                        Of
                        {{ $hosts->lastPage() }}
                    </div>

                    <div class="col-lg-12 text-center">
                        {{ $hosts->appends(Request::all())->render() }}
                    </div>

                </div>
            @else
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title ">No Hosts</h4>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

@push('scripts')
    <script>
    </script>
@endpush