routes/admin.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'auth'], function () {
    Route::any('/login', ['middleware' => 'guest', 'uses' => 'AuthController@login'])->name('admin.auth.login');
    Route::any('/register', ['middleware' => 'guest', 'uses' => 'AuthController@register'])->name('admin.auth.register');
    Route::post('/logout', ['middleware' => 'auth:backend', 'uses' => 'AuthController@logout'])->name('admin.auth.logout');
});

Route::middleware('auth:backend')->group(function () {
    Route::get('/', 'DashboardController@index')->name('admin.index');
    Route::resource('hosts', 'HostController')->middleware('can:manage.hosts');
    Route::prefix('appointments')->group(function () {
        Route::get('/', 'AppointmentsController@index')->name('admin.appointments.index');
        Route::get('/{id}/show', 'AppointmentsController@show')->name('admin.appointments.show');
        Route::post('/create', 'AppointmentsController@store')->middleware('can:manage.appointments')->name('admin.appointments.store');
        Route::get('/create', 'AppointmentsController@create')->middleware('can:manage.appointments')->name('admin.appointments.create');
        Route::post('/{id}/update', 'AppointmentsController@update')->middleware('can:manage.appointments')->name('admin.appointments.update');
        Route::post('/{id}/reserve', 'AppointmentsController@reserve')->name('admin.appointments.reserve');
        Route::post('/{id}/cancel', 'AppointmentsController@cancel')->name('admin.appointments.cancel');
    });
});

routes/web.php
<?php


use Firebase\JWT\JWT;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth:backend')->namespace('Frontend')->group(function () {
    Route::get('/', function () {
        return redirect()->route('admin.index');
    })->name('index');
    Route::get('/meeting/{id}/join', 'MeetingsController@handle')->name('meetings.join');
    Route::get('/meeting/{id}/host', 'MeetingsController@handle')->name('meetings.host');
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Appointments | Dashboard | @yield('title')</title>
    @section('meta')
        <meta name="title" content="Fleet Management | Dashboard">
        <meta name="description" content="Fleet Management Bus bookings">
    @show
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport'/>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css">
    <link href="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css">
    <link href="{{asset('public/admin_assets/css/material-dashboard.css?v=2.1.2')}}" rel="stylesheet"/>
    <link href="{{asset('public/admin_assets/demo/demo.css')}}" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{{asset('public/admin_assets/js/core/popper.min.js')}}"></script>
    <script src="{{asset('public/admin_assets/js/core/bootstrap-material-design.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>
    {{--<script src="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.js"></script>--}}

    @stack('styles')
</head>
<body class="">
<div class="wrapper ">
    @include('admin.layouts.sidebar')
    <div class="main-panel">
        @include('admin.layouts.header')
        @yield('content')
    </div>
</div>
@stack('scripts')
</body>
</html>

resources/views/admin/layouts/header.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li>
                    <a href="{{ route('admin.auth.logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                        <i class="icon-key"></i> Log Out </a>

                    <form id="logout-form" action="{{ route('admin.auth.logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>

                </li>
            </ul>
        </div>
    </div>
</nav>




 

resources/views/admin/layouts/messages.blade.php
@if (session('status'))
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {!! session()->get("status") !!}
            </div>
        </div>
    </div>
@endif

@if($errors->any())
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {!! implode(' <br /> ', $errors->all()) !!}
            </div>
        </div>
    </div>
@endif

resources/views/admin/layouts/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
    <div class="logo"><a href="{{route('admin.index')}}" class="simple-text logo-normal">
            Appointments App
        </a></div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item  {{(Request::is('backend') ? 'active open' : '')}}">
                <a class="nav-link" href="{{route('admin.index')}}">
                    <i class="material-icons">dashboard</i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item {{(Request::is('backend/appointments*') ? 'active' : '')}} ">
                <a class="nav-link" href="{{route('admin.appointments.index')}}">
                    <i class="material-icons">content_paste</i>
                    <p>Appointments</p>
                </a>
            </li>
            @can('manage.hosts')
                <li class="nav-item {{(Request::is('backend/hosts*') ? 'active' : '')}} ">
                    <a class="nav-link" href="{{route('hosts.index')}}">
                        <i class="material-icons">person</i>
                        <p>Hosts</p>
                    </a>
                </li>
            @endcan
        </ul>
    </div>
</div>